- name: Install required packages (CentOS 7)
  become: yes
  yum:
    state: present
    name:
      - qemu-kvm
      - qemu-img
      - libvirt
      - libvirt-python
      - libguestfs-tools
      - virt-install
      - virt-top
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == "7"

- name: Install required packages (CentOS 8)
  become: yes
  dnf:
    state: present
    name:
      - qemu-kvm
      - qemu-img
      - libvirt
      - python3-libvirt
      - libguestfs-tools
      - virt-install
      - virt-top
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == "8"

- name: Start libvirtd service
  become: yes
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: Install virt-manager
  become: yes
  when: owox_kvm_host_install_virt_manager|bool == True
  yum:
    state: present
    name:
      - virt-manager
      - xorg-x11-xauth
      - dejavu-lgc-sans-fonts
