# Gather facts about storage pools
# Facts will be available as 'ansible_libvirt_pools'
- name: Check current pools
  virt_pool:
    command: facts

- name: Check if we already have pools
  debug:
    var: ansible_libvirt_pools
  loop: "{{ libvirt_storage_pools }}"

- name: Define a new storage pool
  become: true
  virt_pool:
    command: define
    name: "{{ item }}"
    xml: '{{ lookup("template", "libvirt_pool.xml") }}'
  loop: "{{ libvirt_storage_pools }}"
  when: ansible_libvirt_pools |length == 0 or 'ansible_libvirt_pools.{{ item }}.state != "active"'

- name: Let's update list of storagepools
  virt_pool:
    command: facts

- name: Build a storage pool if it does not exist
  become: true
  virt_pool:
    command: build
    name: "{{ item }}"
  loop: "{{ libvirt_storage_pools }}"
  when: 'ansible_libvirt_pools.{{ item }}.state | default("new") != "active"'

- name: Start a storage pool
  virt_pool:
    autostart: yes
    state: active
    name: "{{ item }}"
  loop: "{{ libvirt_storage_pools }}"
  when: 'ansible_libvirt_pools.{{ item }}.state | default("new") != "active"'

- name: Ensure that a given pool will be started at boot
  virt_pool:
    autostart: yes
    name: "{{ item }}"
  loop: "{{ libvirt_storage_pools }}"
  when: 'ansible_libvirt_pools.{{ item }}.autostart == "no"'
